// <auto-generated />
using Catalog.Persistance.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.Persistance.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Products", "Catalog");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Description for product 1",
                            Name = "Product 1",
                            Price = 908m
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Description for product 2",
                            Name = "Product 2",
                            Price = 966m
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Description for product 3",
                            Name = "Product 3",
                            Price = 799m
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Description for product 4",
                            Name = "Product 4",
                            Price = 305m
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Description for product 5",
                            Name = "Product 5",
                            Price = 768m
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "Description for product 6",
                            Name = "Product 6",
                            Price = 353m
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "Description for product 7",
                            Name = "Product 7",
                            Price = 254m
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "Description for product 8",
                            Name = "Product 8",
                            Price = 334m
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "Description for product 9",
                            Name = "Product 9",
                            Price = 461m
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "Description for product 10",
                            Name = "Product 10",
                            Price = 133m
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "Description for product 11",
                            Name = "Product 11",
                            Price = 599m
                        },
                        new
                        {
                            ProductId = 12,
                            Description = "Description for product 12",
                            Name = "Product 12",
                            Price = 312m
                        },
                        new
                        {
                            ProductId = 13,
                            Description = "Description for product 13",
                            Name = "Product 13",
                            Price = 736m
                        },
                        new
                        {
                            ProductId = 14,
                            Description = "Description for product 14",
                            Name = "Product 14",
                            Price = 592m
                        },
                        new
                        {
                            ProductId = 15,
                            Description = "Description for product 15",
                            Name = "Product 15",
                            Price = 375m
                        },
                        new
                        {
                            ProductId = 16,
                            Description = "Description for product 16",
                            Name = "Product 16",
                            Price = 219m
                        },
                        new
                        {
                            ProductId = 17,
                            Description = "Description for product 17",
                            Name = "Product 17",
                            Price = 653m
                        },
                        new
                        {
                            ProductId = 18,
                            Description = "Description for product 18",
                            Name = "Product 18",
                            Price = 480m
                        },
                        new
                        {
                            ProductId = 19,
                            Description = "Description for product 19",
                            Name = "Product 19",
                            Price = 552m
                        },
                        new
                        {
                            ProductId = 20,
                            Description = "Description for product 20",
                            Name = "Product 20",
                            Price = 674m
                        },
                        new
                        {
                            ProductId = 21,
                            Description = "Description for product 21",
                            Name = "Product 21",
                            Price = 787m
                        },
                        new
                        {
                            ProductId = 22,
                            Description = "Description for product 22",
                            Name = "Product 22",
                            Price = 423m
                        },
                        new
                        {
                            ProductId = 23,
                            Description = "Description for product 23",
                            Name = "Product 23",
                            Price = 550m
                        },
                        new
                        {
                            ProductId = 24,
                            Description = "Description for product 24",
                            Name = "Product 24",
                            Price = 570m
                        },
                        new
                        {
                            ProductId = 25,
                            Description = "Description for product 25",
                            Name = "Product 25",
                            Price = 782m
                        },
                        new
                        {
                            ProductId = 26,
                            Description = "Description for product 26",
                            Name = "Product 26",
                            Price = 549m
                        },
                        new
                        {
                            ProductId = 27,
                            Description = "Description for product 27",
                            Name = "Product 27",
                            Price = 606m
                        },
                        new
                        {
                            ProductId = 28,
                            Description = "Description for product 28",
                            Name = "Product 28",
                            Price = 152m
                        },
                        new
                        {
                            ProductId = 29,
                            Description = "Description for product 29",
                            Name = "Product 29",
                            Price = 175m
                        },
                        new
                        {
                            ProductId = 30,
                            Description = "Description for product 30",
                            Name = "Product 30",
                            Price = 709m
                        },
                        new
                        {
                            ProductId = 31,
                            Description = "Description for product 31",
                            Name = "Product 31",
                            Price = 296m
                        },
                        new
                        {
                            ProductId = 32,
                            Description = "Description for product 32",
                            Name = "Product 32",
                            Price = 510m
                        },
                        new
                        {
                            ProductId = 33,
                            Description = "Description for product 33",
                            Name = "Product 33",
                            Price = 707m
                        },
                        new
                        {
                            ProductId = 34,
                            Description = "Description for product 34",
                            Name = "Product 34",
                            Price = 416m
                        },
                        new
                        {
                            ProductId = 35,
                            Description = "Description for product 35",
                            Name = "Product 35",
                            Price = 581m
                        },
                        new
                        {
                            ProductId = 36,
                            Description = "Description for product 36",
                            Name = "Product 36",
                            Price = 378m
                        },
                        new
                        {
                            ProductId = 37,
                            Description = "Description for product 37",
                            Name = "Product 37",
                            Price = 683m
                        },
                        new
                        {
                            ProductId = 38,
                            Description = "Description for product 38",
                            Name = "Product 38",
                            Price = 617m
                        },
                        new
                        {
                            ProductId = 39,
                            Description = "Description for product 39",
                            Name = "Product 39",
                            Price = 242m
                        },
                        new
                        {
                            ProductId = 40,
                            Description = "Description for product 40",
                            Name = "Product 40",
                            Price = 414m
                        },
                        new
                        {
                            ProductId = 41,
                            Description = "Description for product 41",
                            Name = "Product 41",
                            Price = 300m
                        },
                        new
                        {
                            ProductId = 42,
                            Description = "Description for product 42",
                            Name = "Product 42",
                            Price = 175m
                        },
                        new
                        {
                            ProductId = 43,
                            Description = "Description for product 43",
                            Name = "Product 43",
                            Price = 389m
                        },
                        new
                        {
                            ProductId = 44,
                            Description = "Description for product 44",
                            Name = "Product 44",
                            Price = 106m
                        },
                        new
                        {
                            ProductId = 45,
                            Description = "Description for product 45",
                            Name = "Product 45",
                            Price = 759m
                        },
                        new
                        {
                            ProductId = 46,
                            Description = "Description for product 46",
                            Name = "Product 46",
                            Price = 108m
                        },
                        new
                        {
                            ProductId = 47,
                            Description = "Description for product 47",
                            Name = "Product 47",
                            Price = 475m
                        },
                        new
                        {
                            ProductId = 48,
                            Description = "Description for product 48",
                            Name = "Product 48",
                            Price = 780m
                        },
                        new
                        {
                            ProductId = 49,
                            Description = "Description for product 49",
                            Name = "Product 49",
                            Price = 751m
                        },
                        new
                        {
                            ProductId = 50,
                            Description = "Description for product 50",
                            Name = "Product 50",
                            Price = 428m
                        },
                        new
                        {
                            ProductId = 51,
                            Description = "Description for product 51",
                            Name = "Product 51",
                            Price = 954m
                        },
                        new
                        {
                            ProductId = 52,
                            Description = "Description for product 52",
                            Name = "Product 52",
                            Price = 598m
                        },
                        new
                        {
                            ProductId = 53,
                            Description = "Description for product 53",
                            Name = "Product 53",
                            Price = 639m
                        },
                        new
                        {
                            ProductId = 54,
                            Description = "Description for product 54",
                            Name = "Product 54",
                            Price = 860m
                        },
                        new
                        {
                            ProductId = 55,
                            Description = "Description for product 55",
                            Name = "Product 55",
                            Price = 192m
                        },
                        new
                        {
                            ProductId = 56,
                            Description = "Description for product 56",
                            Name = "Product 56",
                            Price = 635m
                        },
                        new
                        {
                            ProductId = 57,
                            Description = "Description for product 57",
                            Name = "Product 57",
                            Price = 479m
                        },
                        new
                        {
                            ProductId = 58,
                            Description = "Description for product 58",
                            Name = "Product 58",
                            Price = 730m
                        },
                        new
                        {
                            ProductId = 59,
                            Description = "Description for product 59",
                            Name = "Product 59",
                            Price = 419m
                        },
                        new
                        {
                            ProductId = 60,
                            Description = "Description for product 60",
                            Name = "Product 60",
                            Price = 600m
                        },
                        new
                        {
                            ProductId = 61,
                            Description = "Description for product 61",
                            Name = "Product 61",
                            Price = 821m
                        },
                        new
                        {
                            ProductId = 62,
                            Description = "Description for product 62",
                            Name = "Product 62",
                            Price = 913m
                        },
                        new
                        {
                            ProductId = 63,
                            Description = "Description for product 63",
                            Name = "Product 63",
                            Price = 782m
                        },
                        new
                        {
                            ProductId = 64,
                            Description = "Description for product 64",
                            Name = "Product 64",
                            Price = 290m
                        },
                        new
                        {
                            ProductId = 65,
                            Description = "Description for product 65",
                            Name = "Product 65",
                            Price = 433m
                        },
                        new
                        {
                            ProductId = 66,
                            Description = "Description for product 66",
                            Name = "Product 66",
                            Price = 865m
                        },
                        new
                        {
                            ProductId = 67,
                            Description = "Description for product 67",
                            Name = "Product 67",
                            Price = 867m
                        },
                        new
                        {
                            ProductId = 68,
                            Description = "Description for product 68",
                            Name = "Product 68",
                            Price = 352m
                        },
                        new
                        {
                            ProductId = 69,
                            Description = "Description for product 69",
                            Name = "Product 69",
                            Price = 543m
                        },
                        new
                        {
                            ProductId = 70,
                            Description = "Description for product 70",
                            Name = "Product 70",
                            Price = 968m
                        },
                        new
                        {
                            ProductId = 71,
                            Description = "Description for product 71",
                            Name = "Product 71",
                            Price = 396m
                        },
                        new
                        {
                            ProductId = 72,
                            Description = "Description for product 72",
                            Name = "Product 72",
                            Price = 875m
                        },
                        new
                        {
                            ProductId = 73,
                            Description = "Description for product 73",
                            Name = "Product 73",
                            Price = 374m
                        },
                        new
                        {
                            ProductId = 74,
                            Description = "Description for product 74",
                            Name = "Product 74",
                            Price = 693m
                        },
                        new
                        {
                            ProductId = 75,
                            Description = "Description for product 75",
                            Name = "Product 75",
                            Price = 771m
                        },
                        new
                        {
                            ProductId = 76,
                            Description = "Description for product 76",
                            Name = "Product 76",
                            Price = 910m
                        },
                        new
                        {
                            ProductId = 77,
                            Description = "Description for product 77",
                            Name = "Product 77",
                            Price = 729m
                        },
                        new
                        {
                            ProductId = 78,
                            Description = "Description for product 78",
                            Name = "Product 78",
                            Price = 457m
                        },
                        new
                        {
                            ProductId = 79,
                            Description = "Description for product 79",
                            Name = "Product 79",
                            Price = 534m
                        },
                        new
                        {
                            ProductId = 80,
                            Description = "Description for product 80",
                            Name = "Product 80",
                            Price = 560m
                        },
                        new
                        {
                            ProductId = 81,
                            Description = "Description for product 81",
                            Name = "Product 81",
                            Price = 323m
                        },
                        new
                        {
                            ProductId = 82,
                            Description = "Description for product 82",
                            Name = "Product 82",
                            Price = 871m
                        },
                        new
                        {
                            ProductId = 83,
                            Description = "Description for product 83",
                            Name = "Product 83",
                            Price = 870m
                        },
                        new
                        {
                            ProductId = 84,
                            Description = "Description for product 84",
                            Name = "Product 84",
                            Price = 230m
                        },
                        new
                        {
                            ProductId = 85,
                            Description = "Description for product 85",
                            Name = "Product 85",
                            Price = 201m
                        },
                        new
                        {
                            ProductId = 86,
                            Description = "Description for product 86",
                            Name = "Product 86",
                            Price = 473m
                        },
                        new
                        {
                            ProductId = 87,
                            Description = "Description for product 87",
                            Name = "Product 87",
                            Price = 331m
                        },
                        new
                        {
                            ProductId = 88,
                            Description = "Description for product 88",
                            Name = "Product 88",
                            Price = 804m
                        },
                        new
                        {
                            ProductId = 89,
                            Description = "Description for product 89",
                            Name = "Product 89",
                            Price = 798m
                        },
                        new
                        {
                            ProductId = 90,
                            Description = "Description for product 90",
                            Name = "Product 90",
                            Price = 862m
                        },
                        new
                        {
                            ProductId = 91,
                            Description = "Description for product 91",
                            Name = "Product 91",
                            Price = 700m
                        },
                        new
                        {
                            ProductId = 92,
                            Description = "Description for product 92",
                            Name = "Product 92",
                            Price = 296m
                        },
                        new
                        {
                            ProductId = 93,
                            Description = "Description for product 93",
                            Name = "Product 93",
                            Price = 167m
                        },
                        new
                        {
                            ProductId = 94,
                            Description = "Description for product 94",
                            Name = "Product 94",
                            Price = 877m
                        },
                        new
                        {
                            ProductId = 95,
                            Description = "Description for product 95",
                            Name = "Product 95",
                            Price = 976m
                        },
                        new
                        {
                            ProductId = 96,
                            Description = "Description for product 96",
                            Name = "Product 96",
                            Price = 308m
                        },
                        new
                        {
                            ProductId = 97,
                            Description = "Description for product 97",
                            Name = "Product 97",
                            Price = 637m
                        },
                        new
                        {
                            ProductId = 98,
                            Description = "Description for product 98",
                            Name = "Product 98",
                            Price = 170m
                        },
                        new
                        {
                            ProductId = 99,
                            Description = "Description for product 99",
                            Name = "Product 99",
                            Price = 861m
                        },
                        new
                        {
                            ProductId = 100,
                            Description = "Description for product 100",
                            Name = "Product 100",
                            Price = 244m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("ProductsInStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductsInStockId"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductsInStockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Stocks", "Catalog");

                    b.HasData(
                        new
                        {
                            ProductsInStockId = 1,
                            ProductId = 1,
                            Stock = 9
                        },
                        new
                        {
                            ProductsInStockId = 2,
                            ProductId = 2,
                            Stock = 0
                        },
                        new
                        {
                            ProductsInStockId = 3,
                            ProductId = 3,
                            Stock = 0
                        },
                        new
                        {
                            ProductsInStockId = 4,
                            ProductId = 4,
                            Stock = 18
                        },
                        new
                        {
                            ProductsInStockId = 5,
                            ProductId = 5,
                            Stock = 2
                        },
                        new
                        {
                            ProductsInStockId = 6,
                            ProductId = 6,
                            Stock = 13
                        },
                        new
                        {
                            ProductsInStockId = 7,
                            ProductId = 7,
                            Stock = 14
                        },
                        new
                        {
                            ProductsInStockId = 8,
                            ProductId = 8,
                            Stock = 2
                        },
                        new
                        {
                            ProductsInStockId = 9,
                            ProductId = 9,
                            Stock = 0
                        },
                        new
                        {
                            ProductsInStockId = 10,
                            ProductId = 10,
                            Stock = 11
                        },
                        new
                        {
                            ProductsInStockId = 11,
                            ProductId = 11,
                            Stock = 16
                        },
                        new
                        {
                            ProductsInStockId = 12,
                            ProductId = 12,
                            Stock = 3
                        },
                        new
                        {
                            ProductsInStockId = 13,
                            ProductId = 13,
                            Stock = 16
                        },
                        new
                        {
                            ProductsInStockId = 14,
                            ProductId = 14,
                            Stock = 11
                        },
                        new
                        {
                            ProductsInStockId = 15,
                            ProductId = 15,
                            Stock = 4
                        },
                        new
                        {
                            ProductsInStockId = 16,
                            ProductId = 16,
                            Stock = 17
                        },
                        new
                        {
                            ProductsInStockId = 17,
                            ProductId = 17,
                            Stock = 9
                        },
                        new
                        {
                            ProductsInStockId = 18,
                            ProductId = 18,
                            Stock = 16
                        },
                        new
                        {
                            ProductsInStockId = 19,
                            ProductId = 19,
                            Stock = 19
                        },
                        new
                        {
                            ProductsInStockId = 20,
                            ProductId = 20,
                            Stock = 2
                        },
                        new
                        {
                            ProductsInStockId = 21,
                            ProductId = 21,
                            Stock = 3
                        },
                        new
                        {
                            ProductsInStockId = 22,
                            ProductId = 22,
                            Stock = 4
                        },
                        new
                        {
                            ProductsInStockId = 23,
                            ProductId = 23,
                            Stock = 10
                        },
                        new
                        {
                            ProductsInStockId = 24,
                            ProductId = 24,
                            Stock = 5
                        },
                        new
                        {
                            ProductsInStockId = 25,
                            ProductId = 25,
                            Stock = 11
                        },
                        new
                        {
                            ProductsInStockId = 26,
                            ProductId = 26,
                            Stock = 13
                        },
                        new
                        {
                            ProductsInStockId = 27,
                            ProductId = 27,
                            Stock = 8
                        },
                        new
                        {
                            ProductsInStockId = 28,
                            ProductId = 28,
                            Stock = 7
                        },
                        new
                        {
                            ProductsInStockId = 29,
                            ProductId = 29,
                            Stock = 19
                        },
                        new
                        {
                            ProductsInStockId = 30,
                            ProductId = 30,
                            Stock = 11
                        },
                        new
                        {
                            ProductsInStockId = 31,
                            ProductId = 31,
                            Stock = 10
                        },
                        new
                        {
                            ProductsInStockId = 32,
                            ProductId = 32,
                            Stock = 11
                        },
                        new
                        {
                            ProductsInStockId = 33,
                            ProductId = 33,
                            Stock = 14
                        },
                        new
                        {
                            ProductsInStockId = 34,
                            ProductId = 34,
                            Stock = 17
                        },
                        new
                        {
                            ProductsInStockId = 35,
                            ProductId = 35,
                            Stock = 17
                        },
                        new
                        {
                            ProductsInStockId = 36,
                            ProductId = 36,
                            Stock = 16
                        },
                        new
                        {
                            ProductsInStockId = 37,
                            ProductId = 37,
                            Stock = 16
                        },
                        new
                        {
                            ProductsInStockId = 38,
                            ProductId = 38,
                            Stock = 12
                        },
                        new
                        {
                            ProductsInStockId = 39,
                            ProductId = 39,
                            Stock = 14
                        },
                        new
                        {
                            ProductsInStockId = 40,
                            ProductId = 40,
                            Stock = 4
                        },
                        new
                        {
                            ProductsInStockId = 41,
                            ProductId = 41,
                            Stock = 16
                        },
                        new
                        {
                            ProductsInStockId = 42,
                            ProductId = 42,
                            Stock = 18
                        },
                        new
                        {
                            ProductsInStockId = 43,
                            ProductId = 43,
                            Stock = 16
                        },
                        new
                        {
                            ProductsInStockId = 44,
                            ProductId = 44,
                            Stock = 8
                        },
                        new
                        {
                            ProductsInStockId = 45,
                            ProductId = 45,
                            Stock = 16
                        },
                        new
                        {
                            ProductsInStockId = 46,
                            ProductId = 46,
                            Stock = 10
                        },
                        new
                        {
                            ProductsInStockId = 47,
                            ProductId = 47,
                            Stock = 0
                        },
                        new
                        {
                            ProductsInStockId = 48,
                            ProductId = 48,
                            Stock = 15
                        },
                        new
                        {
                            ProductsInStockId = 49,
                            ProductId = 49,
                            Stock = 11
                        },
                        new
                        {
                            ProductsInStockId = 50,
                            ProductId = 50,
                            Stock = 6
                        },
                        new
                        {
                            ProductsInStockId = 51,
                            ProductId = 51,
                            Stock = 11
                        },
                        new
                        {
                            ProductsInStockId = 52,
                            ProductId = 52,
                            Stock = 11
                        },
                        new
                        {
                            ProductsInStockId = 53,
                            ProductId = 53,
                            Stock = 10
                        },
                        new
                        {
                            ProductsInStockId = 54,
                            ProductId = 54,
                            Stock = 15
                        },
                        new
                        {
                            ProductsInStockId = 55,
                            ProductId = 55,
                            Stock = 10
                        },
                        new
                        {
                            ProductsInStockId = 56,
                            ProductId = 56,
                            Stock = 7
                        },
                        new
                        {
                            ProductsInStockId = 57,
                            ProductId = 57,
                            Stock = 17
                        },
                        new
                        {
                            ProductsInStockId = 58,
                            ProductId = 58,
                            Stock = 17
                        },
                        new
                        {
                            ProductsInStockId = 59,
                            ProductId = 59,
                            Stock = 1
                        },
                        new
                        {
                            ProductsInStockId = 60,
                            ProductId = 60,
                            Stock = 0
                        },
                        new
                        {
                            ProductsInStockId = 61,
                            ProductId = 61,
                            Stock = 13
                        },
                        new
                        {
                            ProductsInStockId = 62,
                            ProductId = 62,
                            Stock = 12
                        },
                        new
                        {
                            ProductsInStockId = 63,
                            ProductId = 63,
                            Stock = 3
                        },
                        new
                        {
                            ProductsInStockId = 64,
                            ProductId = 64,
                            Stock = 7
                        },
                        new
                        {
                            ProductsInStockId = 65,
                            ProductId = 65,
                            Stock = 18
                        },
                        new
                        {
                            ProductsInStockId = 66,
                            ProductId = 66,
                            Stock = 0
                        },
                        new
                        {
                            ProductsInStockId = 67,
                            ProductId = 67,
                            Stock = 0
                        },
                        new
                        {
                            ProductsInStockId = 68,
                            ProductId = 68,
                            Stock = 15
                        },
                        new
                        {
                            ProductsInStockId = 69,
                            ProductId = 69,
                            Stock = 6
                        },
                        new
                        {
                            ProductsInStockId = 70,
                            ProductId = 70,
                            Stock = 14
                        },
                        new
                        {
                            ProductsInStockId = 71,
                            ProductId = 71,
                            Stock = 13
                        },
                        new
                        {
                            ProductsInStockId = 72,
                            ProductId = 72,
                            Stock = 11
                        },
                        new
                        {
                            ProductsInStockId = 73,
                            ProductId = 73,
                            Stock = 16
                        },
                        new
                        {
                            ProductsInStockId = 74,
                            ProductId = 74,
                            Stock = 5
                        },
                        new
                        {
                            ProductsInStockId = 75,
                            ProductId = 75,
                            Stock = 0
                        },
                        new
                        {
                            ProductsInStockId = 76,
                            ProductId = 76,
                            Stock = 13
                        },
                        new
                        {
                            ProductsInStockId = 77,
                            ProductId = 77,
                            Stock = 6
                        },
                        new
                        {
                            ProductsInStockId = 78,
                            ProductId = 78,
                            Stock = 4
                        },
                        new
                        {
                            ProductsInStockId = 79,
                            ProductId = 79,
                            Stock = 13
                        },
                        new
                        {
                            ProductsInStockId = 80,
                            ProductId = 80,
                            Stock = 18
                        },
                        new
                        {
                            ProductsInStockId = 81,
                            ProductId = 81,
                            Stock = 14
                        },
                        new
                        {
                            ProductsInStockId = 82,
                            ProductId = 82,
                            Stock = 9
                        },
                        new
                        {
                            ProductsInStockId = 83,
                            ProductId = 83,
                            Stock = 4
                        },
                        new
                        {
                            ProductsInStockId = 84,
                            ProductId = 84,
                            Stock = 16
                        },
                        new
                        {
                            ProductsInStockId = 85,
                            ProductId = 85,
                            Stock = 2
                        },
                        new
                        {
                            ProductsInStockId = 86,
                            ProductId = 86,
                            Stock = 1
                        },
                        new
                        {
                            ProductsInStockId = 87,
                            ProductId = 87,
                            Stock = 17
                        },
                        new
                        {
                            ProductsInStockId = 88,
                            ProductId = 88,
                            Stock = 10
                        },
                        new
                        {
                            ProductsInStockId = 89,
                            ProductId = 89,
                            Stock = 0
                        },
                        new
                        {
                            ProductsInStockId = 90,
                            ProductId = 90,
                            Stock = 11
                        },
                        new
                        {
                            ProductsInStockId = 91,
                            ProductId = 91,
                            Stock = 12
                        },
                        new
                        {
                            ProductsInStockId = 92,
                            ProductId = 92,
                            Stock = 0
                        },
                        new
                        {
                            ProductsInStockId = 93,
                            ProductId = 93,
                            Stock = 16
                        },
                        new
                        {
                            ProductsInStockId = 94,
                            ProductId = 94,
                            Stock = 19
                        },
                        new
                        {
                            ProductsInStockId = 95,
                            ProductId = 95,
                            Stock = 2
                        },
                        new
                        {
                            ProductsInStockId = 96,
                            ProductId = 96,
                            Stock = 11
                        },
                        new
                        {
                            ProductsInStockId = 97,
                            ProductId = 97,
                            Stock = 11
                        },
                        new
                        {
                            ProductsInStockId = 98,
                            ProductId = 98,
                            Stock = 10
                        },
                        new
                        {
                            ProductsInStockId = 99,
                            ProductId = 99,
                            Stock = 1
                        },
                        new
                        {
                            ProductsInStockId = 100,
                            ProductId = 100,
                            Stock = 15
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Navigation("Stock")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
